build:
    environment:
        php:
            version: 7.1
    tests:
        override:
            -
                command: 'phpunit'
checks:
    php:
        code_rating: true
        duplication: true
