build:
    environment:
        php:
            version: 7.0
    tests:
        override:
            -
                command: 'vendor/bin/phpunit'
checks:
    php:
        code_rating: true
        duplication: true
